### ISSUE TITLE
Getting Text/Content/Other Address REcords

### ISSUE THREAD

**Issue by thelamer** [merklejerk/ez-ens#1]
Also with the introduction of Text records and multi coin can options be passed to return those ? 
https://medium.com/the-ethereum-name-service/new-text-records-now-available-for-ens-names-in-manager-a0ebb9cda73a
https://medium.com/the-ethereum-name-service/ens-launches-multi-coin-support-15-wallets-to-integrate-92518ab20599

Using Web3@next I see functions for pulling text: 
https://web3js.readthedocs.io/en/v2.0.0-alpha/web3-eth-ens.html#gettext
Though I am not able to get this working locally, I must admit though I am rather inexperienced.

**Comment by merklejerk** [comment]
That's interesting. I didn't know Web3 had native ENS support now. That's pretty rad.

In any event, I've added some [extra functions](https://github.com/merklejerk/ez-ens#resolver-eip-support) for text records and multi-coin to this package for convenience.

**Comment by thelamer** [comment]
Works like a charm, thanks for looking into this!
